[package]
name = "parley"
version = "0.0.1"
authors = ["Chad Brokaw <cbrokaw@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
swash = "0.1.8"
peniko = { git = "https://github.com/linebender/peniko", rev = "df3a16e4f5dd8a179410a61056e40a6643ea094e" }

[workspace]
members = ["piet-parley"]
